import fs from 'node:fs/promises'
import path from 'node:path'
import type { NpmrcConfig } from '../shared/types'

export const npmrcPathForProject = (projectDir: string) => path.join(projectDir, '.npmrc')

export const parseNpmrc = (text: string): NpmrcConfig => {
  const cfg: NpmrcConfig = { values: {}, scopedRegistries: {} }
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim()
    if (!line || line.startsWith('#') || line.startsWith(';')) continue
    const idx = line.indexOf('=')
    if (idx <= 0) continue
    const key = line.slice(0, idx).trim()
    const value = line.slice(idx + 1).trim()

    if (key.endsWith(':registry') && key.startsWith('@')) {
      const scope = key.slice(0, -':registry'.length)
      if (scope) cfg.scopedRegistries[scope] = value
      continue
    }
    cfg.values[key] = value
  }
  return cfg
}

export const serializeNpmrc = (cfg: NpmrcConfig): string => {
  const lines: string[] = []
  lines.push('# Generated by Unreal Package Manager (Desktop)')
  const preferredKeys = ['registry', 'proxy', 'https-proxy', 'strict-ssl']
  const emitted = new Set<string>()

  for (const k of preferredKeys) {
    const v = cfg.values?.[k]?.trim()
    if (v) {
      lines.push(`${k}=${v}`)
      emitted.add(k)
    } else if (k === 'strict-ssl' && cfg.values?.[k] === 'false') {
      lines.push('strict-ssl=false')
      emitted.add(k)
    }
  }

  const otherKeys = Object.keys(cfg.values ?? {})
    .filter((k) => !emitted.has(k) && !preferredKeys.includes(k))
    .sort()
  for (const k of otherKeys) {
    const v = cfg.values[k]
    if (typeof v === 'string' && v.length) lines.push(`${k}=${v}`)
  }

  const scopes = Object.keys(cfg.scopedRegistries ?? {}).sort()
  for (const scope of scopes) {
    const v = cfg.scopedRegistries[scope]?.trim()
    if (!v) continue
    lines.push(`${scope}:registry=${v}`)
  }
  lines.push('')
  return lines.join('\n')
}

export const loadProjectNpmrc = async (projectDir: string): Promise<NpmrcConfig> => {
  try {
    const raw = await fs.readFile(npmrcPathForProject(projectDir), 'utf8')
    return parseNpmrc(raw)
  } catch {
    return { values: {}, scopedRegistries: {} }
  }
}

export const saveProjectNpmrc = async (projectDir: string, cfg: NpmrcConfig) => {
  await fs.writeFile(npmrcPathForProject(projectDir), serializeNpmrc(cfg), 'utf8')
}
